require('dotenv').config();
const mongoose = require('mongoose');
const User = require('./models/User');

const seedUsers = [
  // --- FAMILY 1: CHAUHAN FAMILY (Vadodara) ---
  {
    fullName: 'Manilal',
    surname: 'Chauhan',
    fatherName: 'Dahyabhai',
    phoneNumber: '+919000000001',
    gender: 'Male',
    dateOfBirth: '1945-08-15',
    nativePlace: 'Karamsad',
    address: 'Chauhan Niwas, Karamsad',
    city: 'Vadodara',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Retired Farmer',
    education: 'Secondary School',
    bloodGroup: 'O+',
    profilePhoto: 'avatar_male_1'
  },
  {
    fullName: 'Rajeshbhai',
    surname: 'Chauhan',
    fatherName: 'Manilal',
    phoneNumber: '+919825010042',
    gender: 'Male',
    dateOfBirth: '1976-12-05',
    nativePlace: 'Karamsad',
    address: 'Vasant Vihar, Gotri Road',
    city: 'Vadodara',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Software Architect',
    education: 'B.E. Computer Engineering',
    bloodGroup: 'B+',
    profilePhoto: 'avatar_male_2'
  },
  {
    fullName: 'Dineshbhai',
    surname: 'Chauhan',
    fatherName: 'Manilal',
    phoneNumber: '+919000000003',
    gender: 'Male',
    dateOfBirth: '1979-04-20',
    nativePlace: 'Karamsad',
    address: 'Ganesh Park, Anand Road',
    city: 'Anand',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Mechanical Engineer',
    education: 'Diploma in Engineering',
    bloodGroup: 'B+',
    profilePhoto: 'avatar_male_1'
  },
  {
    fullName: 'Krupal',
    surname: 'Chauhan',
    fatherName: 'Dineshbhai',
    phoneNumber: '+919000000004',
    gender: 'Male',
    dateOfBirth: '2005-09-14',
    nativePlace: 'Karamsad',
    address: 'Ganesh Park, Anand Road',
    city: 'Anand',
    state: 'Gujarat',
    maritalStatus: 'Single',
    occupation: 'College Student',
    education: 'B.Sc Computer Science',
    bloodGroup: 'A+',
    profilePhoto: 'avatar_male_2'
  },
  {
    fullName: 'Nikita',
    surname: 'Chauhan',
    fatherName: 'Dineshbhai',
    phoneNumber: '+919000000005',
    gender: 'Female',
    dateOfBirth: '2001-03-30',
    nativePlace: 'Karamsad',
    address: 'Ganesh Park, Anand Road',
    city: 'Anand',
    state: 'Gujarat',
    maritalStatus: 'Single',
    occupation: 'Chartered Accountant',
    education: 'Chartered Accountancy (CA)',
    bloodGroup: 'B+',
    profilePhoto: 'avatar_female_1'
  },

  // --- FAMILY 2: JAIN FAMILY (Ahmedabad / Mumbai) ---
  {
    fullName: 'Hasmukh',
    surname: 'Jain',
    fatherName: 'Mohanlal',
    phoneNumber: '+919000000006',
    gender: 'Male',
    dateOfBirth: '1950-10-10',
    nativePlace: 'Vaso',
    address: 'Jain Villa, Ashram Road',
    city: 'Ahmedabad',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Retired Business Owner',
    education: 'B.Com',
    bloodGroup: 'O+',
    profilePhoto: 'avatar_male_1'
  },
  {
    fullName: 'Ramesh',
    surname: 'Jain',
    fatherName: 'Hasmukh',
    phoneNumber: '+919000000007',
    gender: 'Male',
    dateOfBirth: '1975-05-18',
    nativePlace: 'Vaso',
    address: 'Gokuldham Heights, Satellite',
    city: 'Ahmedabad',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Diamond Merchant',
    education: 'MBA in Finance',
    bloodGroup: 'AB+',
    profilePhoto: 'avatar_male_2'
  },
  {
    fullName: 'Suman',
    surname: 'Jain',
    fatherName: 'Shantilal',
    phoneNumber: '+919000000008',
    gender: 'Female',
    dateOfBirth: '1980-08-22',
    nativePlace: 'Dharmaj',
    address: 'Gokuldham Heights, Satellite',
    city: 'Ahmedabad',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Homemaker',
    education: 'B.A. Literature',
    bloodGroup: 'A+',
    profilePhoto: 'avatar_female_1'
  },
  {
    fullName: 'Amit',
    surname: 'Jain',
    fatherName: 'Ramesh',
    phoneNumber: '+919000000009',
    gender: 'Male',
    dateOfBirth: '2004-11-12',
    nativePlace: 'Vaso',
    address: 'Gokuldham Heights, Satellite',
    city: 'Ahmedabad',
    state: 'Gujarat',
    maritalStatus: 'Single',
    occupation: 'Medical Student',
    education: 'MBBS (Pursuing)',
    bloodGroup: 'AB+',
    profilePhoto: 'avatar_male_1'
  },
  {
    fullName: 'Nehal',
    surname: 'Jain',
    fatherName: 'Ramesh',
    phoneNumber: '+919000000010',
    gender: 'Female',
    dateOfBirth: '2008-01-15',
    nativePlace: 'Vaso',
    address: 'Gokuldham Heights, Satellite',
    city: 'Ahmedabad',
    state: 'Gujarat',
    maritalStatus: 'Single',
    occupation: 'High School Student',
    education: 'Secondary School',
    bloodGroup: 'A+',
    profilePhoto: 'avatar_female_1'
  },

  // --- FAMILY 3: PATEL FAMILY (Karamsad / Anand) ---
  {
    fullName: 'Babubhai',
    surname: 'Patel',
    fatherName: 'Muljibhai',
    phoneNumber: '+919000000011',
    gender: 'Male',
    dateOfBirth: '1948-02-14',
    nativePlace: 'Karamsad',
    address: 'Patidar Farm, Karamsad',
    city: 'Anand',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Senior Farmer',
    education: 'Primary School',
    bloodGroup: 'B+',
    profilePhoto: 'avatar_male_1'
  },
  {
    fullName: 'Arvind',
    surname: 'Patel',
    fatherName: 'Babubhai',
    phoneNumber: '+919000000012',
    gender: 'Male',
    dateOfBirth: '1972-09-09',
    nativePlace: 'Karamsad',
    address: 'Shanti Villa, Vallabh Vidyanagar',
    city: 'Anand',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Professor of Physics',
    education: 'Ph.D in Physics',
    bloodGroup: 'B+',
    profilePhoto: 'avatar_male_2'
  },
  {
    fullName: 'Savitaben',
    surname: 'Patel',
    fatherName: 'Somabhai',
    phoneNumber: '+919000000013',
    gender: 'Female',
    dateOfBirth: '1975-06-06',
    nativePlace: 'Petlad',
    address: 'Shanti Villa, Vallabh Vidyanagar',
    city: 'Anand',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'High School Teacher',
    education: 'B.Ed & M.Sc Math',
    bloodGroup: 'O-',
    profilePhoto: 'avatar_female_1'
  },
  {
    fullName: 'Rishi',
    surname: 'Patel',
    fatherName: 'Arvind',
    phoneNumber: '+919000000014',
    gender: 'Male',
    dateOfBirth: '2000-05-25',
    nativePlace: 'Karamsad',
    address: 'Shanti Villa, Vallabh Vidyanagar',
    city: 'Anand',
    state: 'Gujarat',
    maritalStatus: 'Single',
    occupation: 'Software Engineer',
    education: 'B.Tech IT',
    bloodGroup: 'B+',
    profilePhoto: 'avatar_male_1'
  },
  {
    fullName: 'Nishaben',
    surname: 'Patel',
    fatherName: 'Arvind',
    phoneNumber: '+919000000015',
    gender: 'Female',
    dateOfBirth: '2003-12-19',
    nativePlace: 'Karamsad',
    address: 'Shanti Villa, Vallabh Vidyanagar',
    city: 'Anand',
    state: 'Gujarat',
    maritalStatus: 'Single',
    occupation: 'Business Analyst',
    education: 'B.BA Operations',
    bloodGroup: 'O-',
    profilePhoto: 'avatar_female_1'
  },

  // --- FAMILY 4: SHAH FAMILY (Surat / Nadiad) ---
  {
    fullName: 'Chimanlal',
    surname: 'Shah',
    fatherName: 'Vithaldas',
    phoneNumber: '+919000000016',
    gender: 'Male',
    dateOfBirth: '1952-11-20',
    nativePlace: 'Narsanda',
    address: 'Shah Sadan, Nadiad',
    city: 'Nadiad',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Retired Textile Merchant',
    education: 'High School',
    bloodGroup: 'A-',
    profilePhoto: 'avatar_male_1'
  },
  {
    fullName: 'Hiralal',
    surname: 'Shah',
    fatherName: 'Chimanlal',
    phoneNumber: '+919000000017',
    gender: 'Male',
    dateOfBirth: '1978-01-24',
    nativePlace: 'Narsanda',
    address: 'Aditya Bungalows, Adajan',
    city: 'Surat',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Textile Factory Owner',
    education: 'B.Sc Textiles',
    bloodGroup: 'B-',
    profilePhoto: 'avatar_male_2'
  },
  {
    fullName: 'Alpaben',
    surname: 'Shah',
    fatherName: 'Keshavlal',
    phoneNumber: '+919000000018',
    gender: 'Female',
    dateOfBirth: '1982-04-12',
    nativePlace: 'Piplav',
    address: 'Aditya Bungalows, Adajan',
    city: 'Surat',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Fashion Designer',
    education: 'Diploma in Fashion Design',
    bloodGroup: 'O+',
    profilePhoto: 'avatar_female_1'
  },
  {
    fullName: 'Dev',
    surname: 'Shah',
    fatherName: 'Hiralal',
    phoneNumber: '+919000000019',
    gender: 'Male',
    dateOfBirth: '2006-03-08',
    nativePlace: 'Narsanda',
    address: 'Aditya Bungalows, Adajan',
    city: 'Surat',
    state: 'Gujarat',
    maritalStatus: 'Single',
    occupation: 'Engineering Student',
    education: 'B.Tech Mechanical',
    bloodGroup: 'B-',
    profilePhoto: 'avatar_male_1'
  },
  {
    fullName: 'Mira',
    surname: 'Shah',
    fatherName: 'Hiralal',
    phoneNumber: '+919000000020',
    gender: 'Female',
    dateOfBirth: '2009-07-28',
    nativePlace: 'Narsanda',
    address: 'Aditya Bungalows, Adajan',
    city: 'Surat',
    state: 'Gujarat',
    maritalStatus: 'Single',
    occupation: 'Middle School Student',
    education: 'Primary School',
    bloodGroup: 'O+',
    profilePhoto: 'avatar_female_1'
  },

  // --- FAMILY 5: MEHTA FAMILY (Rajkot) ---
  {
    fullName: 'Jayantilal',
    surname: 'Mehta',
    fatherName: 'Nanji',
    phoneNumber: '+919000000021',
    gender: 'Male',
    dateOfBirth: '1954-12-30',
    nativePlace: 'Bhalej',
    address: 'Mehta Nivas, Bhalej Road',
    city: 'Rajkot',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Retired Banker',
    education: 'M.Com Banking',
    bloodGroup: 'AB-',
    profilePhoto: 'avatar_male_1'
  },
  {
    fullName: 'Sanjay',
    surname: 'Mehta',
    fatherName: 'Jayantilal',
    phoneNumber: '+919000000022',
    gender: 'Male',
    dateOfBirth: '1980-07-07',
    nativePlace: 'Bhalej',
    address: 'Sadguru Flats, Kalawad Road',
    city: 'Rajkot',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Chartered Accountant',
    education: 'FCA, B.Com',
    bloodGroup: 'B+',
    profilePhoto: 'avatar_male_2'
  },
  {
    fullName: 'Geetaben',
    surname: 'Mehta',
    fatherName: 'Dayalji',
    phoneNumber: '+919000000023',
    gender: 'Female',
    dateOfBirth: '1984-03-03',
    nativePlace: 'Ode',
    address: 'Sadguru Flats, Kalawad Road',
    city: 'Rajkot',
    state: 'Gujarat',
    maritalStatus: 'Married',
    occupation: 'Primary School Teacher',
    education: 'M.A., B.Ed',
    bloodGroup: 'A+',
    profilePhoto: 'avatar_female_1'
  },
  {
    fullName: 'Harish',
    surname: 'Mehta',
    fatherName: 'Sanjay',
    phoneNumber: '+919000000024',
    gender: 'Male',
    dateOfBirth: '2010-09-12',
    nativePlace: 'Bhalej',
    address: 'Sadguru Flats, Kalawad Road',
    city: 'Rajkot',
    state: 'Gujarat',
    maritalStatus: 'Single',
    occupation: 'Primary School Student',
    education: 'Primary School',
    bloodGroup: 'B+',
    profilePhoto: 'avatar_male_1'
  },
  {
    fullName: 'Deepa',
    surname: 'Mehta',
    fatherName: 'Sanjay',
    phoneNumber: '+919000000025',
    gender: 'Female',
    dateOfBirth: '2014-05-15',
    nativePlace: 'Bhalej',
    address: 'Sadguru Flats, Kalawad Road',
    city: 'Rajkot',
    state: 'Gujarat',
    maritalStatus: 'Single',
    occupation: 'Primary School Student',
    education: 'Primary School',
    bloodGroup: 'A+',
    profilePhoto: 'avatar_female_1'
  }
];

const seedDatabase = async () => {
  const uri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/kutumbsetu';
  console.log('Seeding: Connecting to database...');
  await mongoose.connect(uri);

  console.log('Seeding: Clearing existing directory records...');
  await mongoose.connection.db.collection('directory').deleteMany({});

  console.log(`Seeding: Inserting ${seedUsers.length} structured family members...`);
  await User.insertMany(seedUsers);

  console.log('Seeding completed successfully!');
  await mongoose.connection.close();
  console.log('Connection closed.');
  process.exit(0);
};

seedDatabase().catch(err => {
  console.error('Seeding error:', err);
  process.exit(1);
});
