// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm2WH22xpOWY-eNQKPTDnWhpTemFoAM0k',
    appId: '1:246467901200:web:d1f9e1cd9268ab4b5d1795',
    messagingSenderId: '246467901200',
    projectId: 'kutumbsetu-final-year-project',
    authDomain: 'kutumbsetu-final-year-project.firebaseapp.com',
    storageBucket: 'kutumbsetu-final-year-project.firebasestorage.app',
    measurementId: 'G-8FQ35FFJLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoKTfIA5tEoBQE4uzIx-6CMftC_WhIkIw',
    appId: '1:246467901200:android:50ef2a14d8d74b355d1795',
    messagingSenderId: '246467901200',
    projectId: 'kutumbsetu-final-year-project',
    storageBucket: 'kutumbsetu-final-year-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm2WH22xpOWY-eNQKPTDnWhpTemFoAM0k',
    appId: '1:246467901200:web:7ce70152b60679955d1795',
    messagingSenderId: '246467901200',
    projectId: 'kutumbsetu-final-year-project',
    authDomain: 'kutumbsetu-final-year-project.firebaseapp.com',
    storageBucket: 'kutumbsetu-final-year-project.firebasestorage.app',
    measurementId: 'G-LD9B318C5R',
  );
}
